# Generated by Django 3.2.5 on 2021-10-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assets',
            table=None,
        ),
    ]
