# Generated by Django 3.2.5 on 2021-10-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognizer_app', '0002_alter_assets_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=50)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
