# Generated by Django 3.2.5 on 2021-10-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'assets',
                'managed': True,
            },
        ),
    ]
